const ENV = {practice:{rest:'https://api-fxpractice.oanda.com',stream:'https://stream-fxpractice.oanda.com'},live:{rest:'https://api-fxtrade.oanda.com',stream:'https://stream-fxtrade.oanda.com'}};
const GRANULARITY={M1:'M1',M3:'M3',M5:'M5',M15:'M15',M30:'M30',H1:'H1',H4:'H4',D1:'D'};
export class OandaProvider {
  constructor({env='practice',accountId,token,instrument='XAU_USD'}){this.env=ENV[env]||ENV.practice;this.accountId=accountId;this.token=token;this.instrument=instrument;this.reader=null;this.abort=null}
  get configured(){return Boolean(this.accountId&&this.token)}
  async request(path,params={}){if(!this.configured)throw new Error('OANDA credentials are not configured');const url=new URL(this.env.rest+path);Object.entries(params).forEach(([k,v])=>url.searchParams.set(k,String(v)));const r=await fetch(url,{headers:{Authorization:`Bearer ${this.token}`,Accept:'application/json'}});if(!r.ok)throw new Error(`OANDA ${r.status}: ${await r.text()}`);return r.json()}
  async getHistoricalCandles(timeframe,count=500){const g=GRANULARITY[timeframe]||'M5';const d=await this.request(`/v3/instruments/${this.instrument}/candles`,{price:'M',granularity:g,count});return (d.candles||[]).map(c=>{const x=c.mid||c.bid||c.ask;return {time:new Date(c.time).getTime(),open:+x.o,high:+x.h,low:+x.l,close:+x.c,volume:Number(c.volume||0),complete:Boolean(c.complete)}})}
  async getCurrentPrice(){const d=await this.request(`/v3/accounts/${this.accountId}/pricing`,{instruments:this.instrument});const p=d.prices?.[0];if(!p)throw new Error('No XAU_USD price returned');return {symbol:'XAUUSD',bid:+p.bids[0].price,ask:+p.asks[0].price,mid:(+p.bids[0].price + +p.asks[0].price)/2,timestamp:p.time}}
  async streamPrices(onPrice,onStatus){if(!this.configured)throw new Error('OANDA credentials are not configured');this.abort=new AbortController();const url=`${this.env.stream}/v3/accounts/${this.accountId}/pricing/stream?instruments=${encodeURIComponent(this.instrument)}`;const r=await fetch(url,{headers:{Authorization:`Bearer ${this.token}`,Accept:'application/octet-stream'},signal:this.abort.signal});if(!r.ok)throw new Error(`OANDA stream ${r.status}: ${await r.text()}`);onStatus?.('LIVE');const reader=r.body.getReader();const decoder=new TextDecoder();let buffer='';try{while(true){const {value,done}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});const lines=buffer.split('\n');buffer=lines.pop()||'';for(const line of lines){if(!line.trim())continue;try{const m=JSON.parse(line);if(m.type==='HEARTBEAT')continue;if(m.type==='PRICE'||m.instrument){const bid=Number(m.bids?.[0]?.price),ask=Number(m.asks?.[0]?.price);if(Number.isFinite(bid)&&Number.isFinite(ask))onPrice({symbol:'XAUUSD',bid,ask,mid:(bid+ask)/2,timestamp:m.time})}}catch{}}}}finally{reader.releaseLock()}}
  stop(){this.abort?.abort()}
}
export {GRANULARITY};
